# Generated by Django 6.1.1 on 2026-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
